workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PACKAGE_NAME: "com.example.wan_android"
        # 添加环境变量，在 Codemagic 控制台设置实际值
        DEEPSEEK_API_KEY: $DEEPSEEK_API_KEY
        # 签名相关环境变量
        KEY_ALIAS: $KEY_ALIAS
        KEY_PASSWORD: $KEY_PASSWORD
        STORE_PASSWORD: $STORE_PASSWORD
        CM_KEYSTORE_PATH: $CM_KEYSTORE_PATH
      groups:
        - cute_ui
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter build apk
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com

  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.wan_android"
        # 添加环境变量，在 Codemagic 控制台设置实际值
        DEEPSEEK_API_KEY: $DEEPSEEK_API_KEY
      groups:
        - cute_ui
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter build ipa
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com 